---
title: "Map_st.Bertin_st.Saint-Germain"
output: html_document
date: "2024-06-12"
---

## Library 

```{r setup, include=FALSE}

library(devtools)
library(htmlwidgets)
library(leaflet)
library(readxl)
library(magrittr)
library(leaflet.extras)
library(dplyr)
library(crosstalk)
library(htmltools)


```

## Import data

```{r cars}

data_PB <- read_excel("data_ren.xlsx")


```


```{r}
data_PB_clean<- data_PB[complete.cases(data_PB$long) & complete.cases(data_PB$lat), ]
```



## Including Plots

```{r pressure, echo=FALSE}

# color pals 
pal.gen <- colorFactor(palette = "Dark2", domain = data_PB_clean$polyp)

# mansi servile percent
data_PB_clean$mansi_servi_procent <- as.numeric(data_PB_clean$mansi_servi_procent)
servile_percent_pal <- colorBin(palette = "RdYlBu", domain = data_PB_clean$mansi_servi_procent, bins = c(0,5,10, 20, 40, 60, 80, 100), na.color = "black", reverse = TRUE)


# Mills pal
data_PB_clean$Mills <- as.numeric(data_PB_clean$Mills)
mills_pal <- colorBin(palette = c("#8B0000","#ff5c5c", "#00FF00"), domain = data_PB_clean$Mills, bins = c(0, 1, 3, 6, 12, 15, 27), na.color = "black", reverse = TRUE)


# Manses total
data_PB_clean$manses_all_servile_ingen <- as.numeric(data_PB_clean$manses_all_servile_ingen)
manses_pal <- colorBin(palette = c("#8B0000","#ff5c5c","#FFA500","#006400", "#00FF00"), domain = data_PB_clean$manses_all_servile_ingen, bins = c(1,20,40,60,80,100,120,140,160,180,300), na.color = "black", reverse = TRUE)

# Mills pr.manse
data_PB_clean$Mill_manse <- as.numeric(data_PB_clean$Mill_manse)
mills_pr_manses_pal <- colorBin(palette = c("#8B0000","#ff5c5c","#FFA500","#006400", "#00FF00"), domain = data_PB_clean$Mill_manse, bins = c(6,12,18,24,30,40,50,60,80,100,120), na.color = "black", reverse = TRUE)


#agerjord_pr_mansi

data_PB_clean$Arable_land_pr_mansi_bun <- as.numeric(data_PB_clean$Arable_land_pr_mansi_bun)
acker_pr_manses_pal <- colorBin(palette = c("#8B0000","#ff5c5c","#FFA500","#006400", "#00FF00"), domain = data_PB_clean$Arable_land_pr_mansi_bun, bins = c(2,4,6,12,14,16,18), na.color = "black", reverse = TRUE)





map <- leaflet(data_PB_clean) %>%
  addTiles() %>%
  addProviderTiles("Esri.WorldImagery", options = providerTileOptions(opacity = 0.5)) %>%
  addCircleMarkers(lng = ~long, lat = ~lat,
                   popup = ~paste("Villae:", estate, "<br>",
                                  "Polyptych:", polyp, "<br>",
                                  "Manses:", manses_all_servile_ingen,"<br>",
                                  "Mills:", Mills,"<br>",
                                  "Name today:", today),
                   group = ~polyp) %>%
  addCircleMarkers(lng = ~long, lat = ~lat,
                   color = ~servile_percent_pal(mansi_servi_procent),
                   popup = ~paste("Villae:", estate, "<br>",
                                  "Polyptych:", polyp, "<br>",
                                  "Manses:", manses_all_servile_ingen,"<br>",
                                  "Mills:", Mills,"<br>",
                                  "Name today:", today),
                   group = "mansi_servi_procent") %>%
  addCircleMarkers(lng = ~long, lat = ~lat,
                   color = ~mills_pr_manses_pal(Mill_manse),
                   popup = ~paste("Villae:", estate, "<br>",
                                  "Polyptych:", polyp, "<br>",
                                  "Manses:", manses_all_servile_ingen,"<br>",
                                  "Mills:", Mills,"<br>",
                                  "Name today:", today),
                   group = "mansi/mill") %>%
  addCircleMarkers(lng = ~long, lat = ~lat,
                   color = ~mills_pal(Mills),
                   popup = ~paste("Villae:", estate, "<br>",
                                  "Polyptych:", polyp, "<br>",
                                  "Manses:", manses_all_servile_ingen,"<br>",
                                  "Mills:", Mills,"<br>",
                                  "Name today:", today),
                   group = "Mills") %>%
  addCircleMarkers(lng = ~long, lat = ~lat,
                   color = ~manses_pal(manses_all_servile_ingen),
                   popup = ~paste("Villae:", estate, "<br>",
                                  "Polyptych:", polyp, "<br>",
                                  "Manses:", manses_all_servile_ingen,"<br>",
                                  "Mills:", Mills,"<br>",
                                  "Name today:", today),
                   group = "Manses") %>%
  addCircleMarkers(lng = ~long, lat = ~lat,
                   color = ~acker_pr_manses_pal(Arable_land_pr_mansi_bun),
                   popup = ~paste("Villae:", estate, "<br>",
                                  "Polyptych:", polyp, "<br>",
                                  "Manses:", manses_all_servile_ingen,"<br>",
                                  "Mills:", Mills,"<br>",
                                  "Name today:", today),
                   group = "Arable land/mansi (bun)") %>%
  addProviderTiles("Esri.OceanBasemap", group = "Ocean") %>%
  addProviderTiles("Esri.WorldPhysical", group = "Physical") %>%
  addProviderTiles("Stadia.StamenTerrainBackground", group = "Terrain") %>%
  addProviderTiles("Esri.WorldShadedRelief", group = "Water") %>%
  addProviderTiles("Esri.WorldImagery", group = "Aerial") %>%
  addProviderTiles("MtbMap", group = "Geo") %>%
  addLayersControl(
    position = "topleft",
    baseGroups = c("Ocean", "Geo", "Aerial", "Physical", "Water", "Terrain"),
    overlayGroups = c("Polyptyque_Saint_Germain_des_Pres", "Polyptychon_saint_Bertin","mansi_servi_procent", "Mills","Manses","Arable land/mansi (bun)","mansi/mill"),
    options = layersControlOptions(collapsed = TRUE),
  )%>%
  addLegend(pal = servile_percent_pal, values = ~mansi_servi_procent, title = "Percentage of servile manses", position = "bottomright", group = "mansi_servi_procent")%>%
  addLegend(pal = mills_pal, values = ~Mills, title = "Number of Mills", position = "bottomright", group = "Mills")%>%
  addLegend(pal = manses_pal, values = ~manses_all_servile_ingen, title = "Number of Manses", position = "bottomright", group = "Manses")%>%
  addLegend(pal = acker_pr_manses_pal, values = ~Arable_land_pr_mansi_bun, title = "Amount of Arable land/manse (bun)", position = "bottomright", group = "Arable land/mansi (bun)")%>%
  addLegend(pal = mills_pr_manses_pal, values = ~Mill_manse, title = "Number of mansi/mill", position = "bottomright", group = "mansi/mill")





# Kombiner slider, kort og tilpasset CSS i et HTML layout
html <- tagList(
  map
)

# Vis HTML layout
browsable(html)

saveWidget(map, file = "leaflet_map.html")

```

map <- map %>%
  addLegend(pal =servile_percent_pal, values = ~mansi_servi_procent, title = "Percent servile mansi", position = "bottomright", group = "mansi_servi_procent")
  














